repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: flutter-format
        name: Flutter Format
        entry: dart format .
        language: system
        types: [dart]
        pass_filenames: false

    -   id: flutter-analyze
        name: Flutter Analyze
        entry: flutter analyze
        language: system
        types: [dart]
        pass_filenames: false

    -   id: flutter-test
        name: Flutter Test
        entry: flutter test
        language: system
        types: [dart]
        pass_filenames: false
